	<div id="footer">
		<div id="footerleft">
		</div>
		<div id="footerright">
			<ul>
				<li><a title="Disclaimer" href="http://www.nuigalway.ie/disclaimer.php">Disclaimer</a></li>
				<li><a title="Privacy" href="http://www.nuigalway.ie/privacy.php">Privacy</a></li>
				<li><a title="Copyright" href="http://www.nuigalway.ie/copyright.php">Copyright</a></li>
				<li><a title="Enquiries / Contacts" href="http://www.nuigalway.ie/contacts.php">Enquiries / Contacts</a></li>
				<li><a title="Accessibility - Accesskey = 0" accesskey="0" href="http://www.nuigalway.ie/accessibility.php">Accessibility</a></li>
			</ul>
		</div>
	</div>
		
	<div id="valid">National University of Ireland, Galway, University Road, Galway, Ireland. Phone: 353 91 524411<br /><span class="arialblacksmall"><!--#config timefmt="%A, %B %d, %Y" -->This page was last updated <!--#echo var="LAST_MODIFIED" -->&nbsp;&nbsp;&nbsp;&nbsp;</span></div>