	<div id="footer">
		<div id="footerleft">
		</div>
		<div id="footerright">
			<ul>
				<li><a title="Séanadh" href="http://www.nuigalway.ie/disclaimer.php?language=gaeilge">Séanadh</a></li>
				<li><a title="Ráiteas Príobháideachta" href="http://www.nuigalway.ie/privacy.php?language=gaeilge">Ráiteas Príobháideachta</a></li>
				<li><a title="Cóipcheart" href="http://www.nuigalway.ie/copyright.php?language=gaeilge">Cóipcheart</a></li>
				<li><a title="Inrochtaineacht [access key '0']" accesskey="0" href="http://www.nuigalway.ie/accessibility.php?language=gaeilge">Inrochtaineacht</a></li>
			</ul>
		</div>
	</div>