<ul id="importantlinks">
  <li class="verdanabold"> &nbsp;&nbsp;Important Links </li>
  <li><span id="linksAbout" class="youarehere"></span> <a accesskey="7" tabindex="9" title="About NUI Galway [access key '7']" href="http://www.nuigalway.ie/about/"> About NUI Galway&nbsp;&rsaquo;&rsaquo; </a> </li>
  <li><span id="linksNews" class="youarehere"></span> <a tabindex="10" title="News &amp; Events" href="http://www.nuigalway.ie/news/"> News &amp; Events&nbsp;&rsaquo;&rsaquo; </a> </li>
  <li><span id="linksLibrary" class="youarehere"></span> <a tabindex="11" title="Library" href="http://www.library.nuigalway.ie/"> Library </a> </li>
  <li><span id="linksAlumni" class="youarehere"></span> <a tabindex="17" title="Alumni &amp; Friends" href="http://www.nuigalway.ie/alumni/"> Alumni &amp; Friends </a> </li>
  <li><span id="linksUniversity" class="youarehere"></span> <a tabindex="18" title="University Foundation" href="http://www.nuigalway.ie/foundation/"> University Foundation </a> </li>
  <li><span id="linksIrish" class="youarehere"></span> <a tabindex="11" title="Irish at NUI Galway" href="http://www.nuigalway.ie/an_ghaeilge_san_ollscoil/"> Irish at NUI Galway </a> </li>
  <li><span id="linksAcademics" class="youarehere"></span> <a tabindex="12" title="Academics &amp; Staff" href="http://www.nuigalway.ie/staff/"> Academics &amp; Staff </a> </li>
  <li><span id="linksOnline" class="youarehere"></span> <a accesskey="9" tabindex="13" title="Online Services  [access key '9']" href="http://www.nuigalway.ie/online_services/"> Online Services&nbsp;&rsaquo;&rsaquo; </a> </li>
  <li><span id="linksSearch" class="youarehere"></span> <a accesskey="8" tabindex="14" title="Search  [access key '8']" href="http://www.nuigalway.ie/search/"> Search </a> </li>
  <li><span id="linksEnquiries" class="youarehere"></span> <a tabindex="15" title="Enquiries &amp; Contacts" href="http://www.nuigalway.ie/contacts.php"> Enquiries &amp; Contacts </a> </li>
  <li><span id="linksVacancies" class="youarehere"></span> <a tabindex="16" title="Vacancies" href="http://www.nuigalway.ie/news/vacancies.php"> Vacancies </a> </li>
  <li><span id="linksExternal" class="youarehere"></span> <a tabindex="19" title="External Links" href="http://www.nuigalway.ie/links.php"> External Links </a> </li>
</ul>
