<script type="text/javascript" src="http://www.nuigalway.ie/includes/skins/2005/mail.js"></script>
<?
if (!$isPortableDevice) {
?>
<script type="text/javascript" src="http://www.nuigalway.ie/includes/skins/2005/event-cache.js"></script>
<script type="text/javascript" src="http://www.nuigalway.ie/includes/skins/2005/detect.js"></script>
<script type="text/javascript" src="http://www.nuigalway.ie/includes/skins/2005/linkSearch.js"></script>
<script type="text/javascript" src="http://www.nuigalway.ie/includes/skins/2005/eventlisteners.js"></script>
<script type="text/javascript" src="http://www.nuigalway.ie/generic/codelib/sarissa/sarissa.js"></script>
<?
}
?>