<script type="text/javascript" src="/includes/mail.js"></script>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
<script type="text/javascript">
_uacct = "UA-859162-1";
urchinTracker();
</script>
<?
if (!$isPortableDevice) {
?>
<script type="text/javascript" src="includes/skins/2005/event-cache.js"></script>
<script type="text/javascript" src="includes/skins/2005/detect.js"></script>
<script type="text/javascript" src="includes/skins/2005/linkSearch.js"></script>
<script type="text/javascript" src="includes/skins/2005/eventlisteners.js"></script>
<script type="text/javascript" src="/generic/codelib/sarissa/sarissa.js"></script>
<?
}
?>