<div class="linedots"><img alt="spacer" src="http://www.nuigalway.ie/images/spacer.png" height="1" /></div>
<div id="logoimage">
  <div id="logo"><a title="O&Eacute; Gaillimh" href="http://www.nuigalway.ie/?language=gaeilge"><img alt="O&Eacute; Gaillimh" src="http://www.nuigalway.ie/images/logos/logo_irish.png" /></a></div>
  <div id="image"><div id="imagecover">
			<div id="imagecontent"><h1 id="imagecontenttext"></h1><div id="imagemarketingcontent"><!--#include virtual="/includes/marketingtext_irish.inc" --></div> </div> 
	</div></div>
 	<div id="browserWarning" class="errormessage"> <img src="http://www.nuigalway.ie/cms/images/caution.png" alt="Warning Icon" /> <p><strong>Warning:</strong> Your browser doesn't support all of the features in this Web site. Please view our <a title="NUI Galway Accessibility Information" href="http://www.nuigalway.ie/accessibility.php">accessibility page</a> for more details.</p></div>
</div>
