<input type="hidden" name="sort" value="Score" />&nbsp;<label for="searchBox"><input type="text" id="searchBox" name="words" title="NUI Galway Search" accesskey="t" tabindex="1" value="Search Web site" /></label>&nbsp;<label for="searchBoxImage"><input title="NUI Galway Search Now" accesskey="s" tabindex="2" name="imageField" id="searchBoxImage" type="image" alt="Search" src="http://www.nuigalway.ie/images/go.png"/></label>
<a href="#" class="whatisthis">&nbsp;&nbsp;[?]<span><strong>WHAT IS THIS?</strong><br/>Performs a search of the Web site.  Search results are displayed on a new page.</span></a>
 							<input type="hidden" name="config" value="htdig" />
							<input type="hidden" name="exclude" value="/csedocs" />
							<input type="hidden" name="method" value="and" />
							<input type="hidden" name="format" value="builtin-long" />