<table width="100%" border="0" cellpadding="5" cellspacing="0" class="tableborder">
              <tr valign="top">
                <td width="50%"><h4>Student Records and Registration Services</h4>
                  <ul class="bulletlist">
                    <li> <a title="Academic Web Service (Timetables, Results, PIN requests)" href="https://www.mis.nuigalway.ie/regexam/mis_web_services_menu.asp?service_filter=STUDENT" target="_blank"> Academic Web Service (Timetables, Results, PIN requests)</a></li>
                    <li><a title="Online Registration" href="http://www.nuigalway.ie/registration/">Online Registration</a></li>
                  </ul>
                  <h4>Student Services</h4>
                  <ul class="bulletlist">
                    <li><a title="Student accommodation" href="http://www.nuigalway.ie/student_services/accommodation_office/">Student accommodation</a></li>
                    <li><a title="Students' Union" href="http://www.su.nuigalway.ie/">Students' Union</a></li>
                    <li> <a title="Student Information Network (SIN)" href="http://www.sin.ie" target="_blank">Student Information Network (SIN)</a> </li>
                  </ul>
                  <h4>Library Services </h4>
                  <ul class="bulletlist">
                    <li> <a title="Library Catalogue" href="http://www.library.nuigalway.ie/"> Library</a></li>
                  </ul>
                  <h4>Careers</h4>
                  <ul class="bulletlist">
                    <li><a href="http://www.nuigalway.ie/careers/">Career Development Centre</a></li>
                </ul></td>
                <td width="50%"><h4>IT  Services</h4>
                  <ul class="bulletlist">
                    <li> <a title="Webmail" href="http://webmail.nuigalway.ie/"> Webmail</a></li>
                    <li><a href="https://printcredit.nuigalway.ie/">Print services   
                    (buy credit, check  balance)</a></li>
                    <li><a title="Printing (Wireless users only)" href="http://www.nuigalway.ie/cs/students/wireless/wireless.html">Wireless (printing, u drive)</a></li>
                    <li><a title="PC Suites Booking" href="http://www.nuigalway.ie/cs/suites/suites.php">PC Suites information</a></li>
                    <li><a title="PC Suites vacant seat and availability information" href="http://rtis.nuigalway.ie:8080/public/suite_usage.jsp?type=Public%20Access">PC Suites real time availability </a><a title="PC Suites Booking" href="http://www.nuigalway.ie/cs/suites/suites.php" target="_blank"></a></li>
                  </ul>
                  <h4>Teaching and Learning</h4>
                  <ul class="bulletlist">
                    <li><a title="Blackboard Learning System" href="http://blackboard.nuigalway.ie/">Blackboard Learning System</a></li>
                  </ul>                  
                  <h4>Search</h4>
                  <ul class="bulletlist">
				    <li> <a title="Search for Buildings, Lecture Theatres, etc." href="http://www.nuigalway.ie/campus_map/"> Campus Map</a> </li>
                    <li> <a title="E-mail (Staff &amp; Student)" href="http://www.nuigalway.ie/search/"> E-mail (Staff &amp; Student)</a> </li>
                    <li> <a title="Phone Book (Staff)" href="http://www.mis.nuigalway.ie/phones/alpha/" target="_blank"> Phone Book (Staff)</a> </li>
                    <li><a title="Web site Search" href="http://www.nuigalway.ie/search/">Web site Search</a></li>
                </ul>                  </td>
              </tr>
              <tr valign="top">
                <td colspan="2">* - <span class="bodysmall">On campus access only</span> </td>
              </tr>
          </table>