<link rel="search" type="application/opensearchdescription+xml" title="NUI Galway Search" href="http://www.nuigalway.ie/web/services/tools/opensearch_service.xml" />
<link rel="alternate stylesheet" type="text/css" href="css/hi_contrast.css" title="highContrast" />
<link rel="alternate stylesheet" type="text/css" href="css/ie5_01.css" title="IE501" />
<link rel="stylesheet" type="text/css" media="handheld" href="css/handheld.css" title="pda" />