<link rel="search" type="application/opensearchdescription+xml" title="NUI Galway Search" href="http://www.nuigalway.ie/web/services/tools/opensearch_service.xml" />
<link rel="alternate stylesheet" type="text/css" href="css/hi_contrast.css" title="highContrast" />
<link rel="alternate stylesheet" type="text/css" href="css/ie5_01.css" title="IE501" />
<?
//PHP changes the default stylesheet to handheld if it's a portable device so don't add this stylesheet.
//The HTML version of this file will have to always add a <link> to handheld.css - see below:
//<link rel="stylesheet" type="text/css" media="handheld" href="css/handheld.css" title="pda" />
?>