<link rel="search" type="application/opensearchdescription+xml" title="NUI Galway Search" href="http://www.nuigalway.ie/web/services/tools/opensearch_service.xml" />
<link rel="alternate stylesheet" type="text/css" href="http://www.nuigalway.ie/css/hi_contrast.css" title="highContrast" />
<link rel="alternate stylesheet" type="text/css" href="http://www.nuigalway.ie/css/ie5_01.css" title="IE501" />
