	<div id="topbar">
		<span id="topbartext">
			<img src="http://www.nuigalway.ie/images/language_grey.png" alt="Leagan Gaeilge" width="11" height="11" /> <a title="Leagan Gaeilge" href="http://www.nuigalway.ie/generic/language_toggle.php?language=gaeilge">Leagan Gaeilge</a> &nbsp;
			<a title="Text Version" href="http://www.nuigalway.ie/parser.php"><img src="http://www.nuigalway.ie/images/text_grey.png" alt="Text Icon" width="11" height="11" /> Text Version</a> &nbsp;
		  <span id="changeFont">
				<img src="http://www.nuigalway.ie/images/display_grey.png" alt="Display Icon" width="11" height="11" /> Display: Zoom
		    <span id="reduceFont">
					<span id="reduceFontButton" class="cursorlinked" title="Zoom Out -">(-)</span>
		    </span>
		    <span id="increaseFont">
					<span id="increaseFontButton" class="cursorlinked" title="Zoom In +">(+)</span>
		    </span>
		  </span>
		  <span id="changeStyle">
		    &nbsp; View ( <span id="cssColour" class="cursorlinked" title="Normal View"> Normal</span> <span id="cssHiContrast" class="cursorlinked" title="High Contrast View"> High contrast</span> )
		  </span>
		</span>
		<span id="topbartextright">
			<a accesskey="p" title="Printer Friendly [access key 'p']" href="http://www.nuigalway.ie/includes/skins/2005/php/printerfriendly.php" target="_blank"><img src="http://www.nuigalway.ie/images/print_box_grey.png" alt="Printer Friendly Version" width="11" height="11" /> Printer Friendly</a>&nbsp;
		  <a title="A to Z" href="http://www.nuigalway.ie/a2z/"><img src="http://www.nuigalway.ie/images/a2z_box_grey.png" alt="A to Z" width="11" height="11" /> A to Z</a>&nbsp;
			<a accesskey="m" title="Sitemap [access key 'm']" href="http://www.nuigalway.ie/sitemap.php"><img src="http://www.nuigalway.ie/images/sitemap_box_grey.png" alt="Sitemap icon" width="11" height="11" /> Sitemap</a> 
		</span>
	</div>