	<div id="topbar">
		<span id="topbartext">
		  <img src="/images/language_grey.png" alt="Language Toggle Icon" width="11" height="11" /> <a title="View in English" href="http://www.nuigalway.ie/generic/language_toggle.php">View in English</a> &nbsp;
			<a title="Text Version" href="/parser.php"><img src="/images/text_grey.png" alt="Text Icon" width="11" height="11" /> Leagan Téacs</a>&nbsp;
		  <span id="changeFont">

				<img src="/images/display_grey.png" alt="Display Icon" width="11" height="11" /> Zúmáil
		    <span id="reduceFont">
					<span id="reduceFontButton" class="cursorlinked" title="Zoom Out -">(-)</span>
		    </span>
		    <span id="increaseFont">
					<span id="increaseFontButton" class="cursorlinked" title="Zoom In +">(+)</span>
		    </span>
			<span id="changeStyle">

				&nbsp; Amharc ( <span id="cssColour" class="cursorlinked" title="Normal View"> Normálta</span> <span id="cssHiContrast" class="cursorlinked" title="High Contrast View"> Ardchodarsnacht</span> )
			</span>
		  </span>
		</span>
		<span id="topbartextright">
			<a title="Priontáil" href="http://www.nuigalway.ie/includes/skins/2005/php/printerfriendly.php?language=gaeilge" target="_blank"><img src="/images/print_box_grey.png" alt="Priontáil" width="11" height="11" /> Priontáil</a>
		</span>
	</div>