<!-- Reverses the language toggle functionality, i.e. index.html = irish & index_irish.html = english -->
	<div id="topbar">
		<span id="topbartext">
		  <img src="http://www.nuigalway.ie/images/language_grey.png" alt="Language Toggle Icon" width="11" height="11" /> <a title="View in English" href="http://www.nuigalway.ie/generic/language_toggle.php?language=gaeilge">View in English</a> &nbsp;
			<a title="Text Version" href="http://www.nuigalway.ie/parser.php"><img src="http://www.nuigalway.ie/images/text_grey.png" alt="Text Icon" width="11" height="11" /> Leagan Téacs</a>&nbsp;
		  <span id="changeFont">

				<img src="http://www.nuigalway.ie/images/display_grey.png" alt="Display Icon" width="11" height="11" /> Zúmáil
		    <span id="reduceFont">
					<span id="reduceFontButton" class="cursorlinked" title="Zoom Out -">(-)</span>
		    </span>
		    <span id="increaseFont">
					<span id="increaseFontButton" class="cursorlinked" title="Zoom In +">(+)</span>
		    </span>
			<span id="changeStyle">

				&nbsp; Amharc ( <span id="cssColour" class="cursorlinked" title="Normal View"> Normálta</span> <span id="cssHiContrast" class="cursorlinked" title="High Contrast View"> Ardchodarsnacht</span> )
			</span>
		  </span>
		</span>
		<span id="topbartextright">

			<a title="Priontáil" href="http://www.nuigalway.ie/includes/skins/2005/php/printerfriendly.php?language=gaeilge" target="_blank"><img src="http://www.nuigalway.ie/images/print_box_grey.png" alt="Priontáil" width="11" height="11" /> Priontáil</a>&nbsp;
		  <a title="A go Z" href="http://www.nuigalway.ie/a2z/?language=gaeilge"><img src="http://www.nuigalway.ie/images/a2z_box_grey.png" alt="A go Z" width="11" height="11" /> A go Z</a>&nbsp;
			<a title="Léarscáil an tSuímh" href="http://www.nuigalway.ie/sitemap.php?language=gaeilge"><img src="http://www.nuigalway.ie/images/sitemap_box_grey.png" alt="Sitemap icon" width="11" height="11" /> Léarscáil an tSuímh</a> 
		</span>
	</div>