<li id="navhome"><a accesskey="1" tabindex="3" title="NUI Galway Home Page [access key '1']" href="http://www.nuigalway.ie/">NUI Galway Home</a></li>
	<li class="activeLI"><span class="active"></span><a title="Landed Estates" href="http://optics.nuigalway.ie/">Landed Estates&nbsp;&rsaquo;&rsaquo;</a>
		<ul id="snSubMenu">
		<!-- Inserted by template converter -->
		<li><span id="link0" class="youarehere"></span><a title="Welcome" href="http://optics.nuigalway.ie/index.html">Welcome</a></li>
		<li><span id="link1" class="youarehere"></span><a title="Staff" href="http://optics.nuigalway.ie/staff.html">Staff</a></li>

	<!-- End of Insertion -->
	</ul>
</li>
