<li id="navhome"><a accesskey="1" tabindex="3" title="O&Eacute; Gaillimh [access key '1']" href="http://www.nuigalway.ie/">O&Eacute; Gaillimh</a></li>
	<li class="activeLI"><span class="active"></span><a title="Landed Estates" href="http://optics.nuigalway.ie/index_irish.html">Landed Estates&nbsp;&rsaquo;&rsaquo;</a>
		<ul id="snSubMenu">
		<!-- Inserted by template converter -->
		<li><span id="link0" class="youarehere"></span><a title="Baile" href="http://optics.nuigalway.ie/index_irish.html">Baile</a></li>
		<li><span id="link1" class="youarehere"></span><a title="Foireann" href="http://optics.nuigalway.ie/staff_irish.html">Foireann</a></li>

	<!-- End of Insertion -->
	</ul>
</li>
